# Generated by Django 2.2.1 on 2019-05-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('about', models.TextField()),
            ],
        ),
    ]
